"""
AI-generated reports for predicted-risk poles.

Each scored pole gets one Report row with:
  id              = "AI-{pole.id}"
  submitted_by    = system user "ai-system"
  severity        = pole.predicted_severity
  description     = narrative built from risk_factors
  location        = pole.address
  title           = "AI Risk Assessment – <severity> – <pole_id>"

The module is safe to call multiple times — it upserts on the
existing report id so re-scoring a pole refreshes the description
without duplicating rows.
"""
from __future__ import annotations

from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import select
from sqlalchemy.orm import Session

from . import orm_models as dbm

# ── System user ───────────────────────────────────────────────────────────────

AI_USER_ID = "ai-system"
_AI_USER_DEFAULTS = dict(
    id=AI_USER_ID,
    name="AI Risk Engine",
    initials="AI",
    role="Predictive Risk System",
)


def ensure_ai_user(db: Session) -> dbm.User:
    """Return the AI system user, creating it if it doesn't exist."""
    user = db.get(dbm.User, AI_USER_ID)
    if not user:
        user = dbm.User(**_AI_USER_DEFAULTS)
        db.add(user)
        db.flush()
    return user


# ── Description generator ─────────────────────────────────────────────────────

_FACTOR_ORDER = ["vegetation", "flood", "storm", "soil", "age", "terrain"]

_FACTOR_LABELS = {
    "vegetation": "Vegetation proximity",
    "flood":      "Waterway / flood proximity",
    "storm":      "Storm & wind exposure",
    "soil":       "Soil drainage",
    "age":        "Asset age",
    "terrain":    "Terrain slope",
}

_FACTOR_DETAIL: dict[str, str] = {
    "vegetation": (
        "Urban forest canopy proximity affects branch encroachment and line-contact risk. "
        "Detroit's densest canopy zones (Grandmont, Rosedale Park, East English Village, "
        "Grosse Pointe) score highest."
    ),
    "flood": (
        "Haversine distance to the nearest OSM waterway centerline (Detroit River, "
        "Rouge River corridor, Clinton River, Lake St. Clair). Closer proximity drives "
        "soil saturation, groundline decay, and flood-load risk."
    ),
    "storm": (
        "Open-Meteo 5-year historical archive: max daily wind gust and precipitation at "
        "this location. Detroit metro baseline is ~78.5 km/h with 2.6 mm avg daily precip."
    ),
    "soil": (
        "Drainage proxy derived from waterway proximity labels. Clay-heavy Detroit River "
        "basin soils drain poorly, accelerating groundline decay."
    ),
    "age": (
        "Score derived from pole installation date. Older poles accumulate fatigue, "
        "wood rot, and coating degradation."
    ),
    "terrain": (
        "USGS EPQS terrain slope at this coordinate. Michigan's flat glacial plain "
        "contributes minimal mechanical stress — this signal is typically near zero."
    ),
}

_SEV_ACTION = {
    "critical": (
        "IMMEDIATE ACTION REQUIRED: This pole is in the top risk band. "
        "Dispatch a crew for physical inspection within 7 days. "
        "Prioritize groundline probe, vegetation clearance assessment, "
        "and structural integrity check."
    ),
    "high": (
        "HIGH PRIORITY: Schedule a field inspection within 30 days. "
        "Focus on waterway-adjacent groundline condition and canopy clearance."
    ),
    "medium": (
        "MODERATE RISK: Include in the next scheduled patrol cycle. "
        "Monitor for vegetation growth and check for visible lean or hardware wear."
    ),
    "low": (
        "LOW RISK: No immediate action required. "
        "Maintain standard patrol interval and re-score annually."
    ),
}


def _fmt_score(score: float | None) -> str:
    return f"{score:.1f}/100" if score is not None else "N/A"


def build_description(pole: dbm.Pole) -> str:
    """Return a human-readable AI risk narrative for the pole."""
    factors: dict = pole.risk_factors or {}
    score = pole.risk_score or 0.0
    sev = (pole.predicted_severity or "medium").lower()

    lines: list[str] = [
        f"Predictive risk assessment generated by Amped Up Risk Engine.",
        f"",
        f"Composite risk score: {score:.1f}/100  →  {sev.upper()}",
        f"",
        "── Risk signal breakdown ──────────────────────────────────────────",
    ]

    for key in _FACTOR_ORDER:
        if key not in factors:
            continue
        f = factors[key]
        label = _FACTOR_LABELS.get(key, key)
        weight = int(round(f.get("weight", 0) * 100))
        fscore = f.get("score")
        detail = _FACTOR_DETAIL.get(key, "")

        # Extra context from the factor dict itself
        extras: list[str] = []
        if key == "flood" and "zone" in f:
            extras.append(f"nearest waterway: {f['zone']}")
        if key == "storm":
            if "max_gust_kmh" in f:
                extras.append(f"max gust {f['max_gust_kmh']:.1f} km/h")
            if "avg_daily_precip_mm" in f:
                extras.append(f"avg precip {f['avg_daily_precip_mm']:.1f} mm/day")
        if key == "terrain" and "slope_pct" in f:
            extras.append(f"slope {f['slope_pct']:.2f}%")

        extra_str = f"  ({', '.join(extras)})" if extras else ""
        lines.append(f"")
        lines.append(f"• {label}  |  weight {weight}%  |  score {_fmt_score(fscore)}{extra_str}")
        lines.append(f"  {detail}")

    composite = factors.get("_composite")
    if composite is not None:
        lines.append(f"")
        lines.append(f"Composite (weighted sum): {composite:.2f}")

    lines += [
        f"",
        "── Recommended action ─────────────────────────────────────────────",
        f"",
        _SEV_ACTION.get(sev, _SEV_ACTION["medium"]),
        f"",
        "── Pole details ───────────────────────────────────────────────────",
        f"",
        f"Classification : {pole.classification}",
        f"Owner          : {pole.owner}",
        f"Circuit        : {pole.circuit}",
        f"Address        : {pole.address}",
        f"Coordinates    : {pole.latitude:.5f} N, {abs(pole.longitude):.5f} W",
    ]

    if pole.installed_at:
        lines.append(f"Installed      : {pole.installed_at.strftime('%Y-%m-%d')}")

    lines += [
        f"",
        "This report was generated automatically. No field photos were collected. "
        "An evaluator should verify findings during the scheduled inspection.",
    ]

    return "\n".join(lines)


# ── Upsert logic ──────────────────────────────────────────────────────────────

AI_REPORT_ID_PREFIX = "AI-"


def upsert_ai_report(db: Session, pole: dbm.Pole) -> dbm.Report:
    """
    Create or update the AI-generated Report for this pole.
    Safe to call repeatedly — always upserts on the same stable id.
    """
    if not pole.risk_score or not pole.predicted_severity:
        raise ValueError(f"Pole {pole.id} has no risk score — score it first.")

    ensure_ai_user(db)

    report_id = f"{AI_REPORT_ID_PREFIX}{pole.id}"
    # Use scalar() to bypass the identity-map cache — avoids UniqueViolation on stale sessions
    report = db.scalar(select(dbm.Report).where(dbm.Report.id == report_id))
    now = datetime.now(timezone.utc)
    sev = dbm.Severity(pole.predicted_severity)

    description = build_description(pole)
    title = f"AI Risk Assessment — {pole.predicted_severity.capitalize()} — {pole.id}"
    location = pole.address or f"{pole.latitude:.4f} N, {abs(pole.longitude):.4f} W"

    if report is None:
        report = dbm.Report(
            id=report_id,
            pole_id=pole.id,
            title=title,
            severity=sev,
            status=dbm.ReportStatus.OPEN,
            submitted_by_user_id=AI_USER_ID,
            submitted_at=now,
            location=location,
            description=description,
        )
        db.add(report)
    else:
        # Refresh title / severity / description on re-score; preserve status
        report.title = title
        report.severity = sev
        report.description = description
        report.location = location

    # Add a history event only when the report is first created
    if report not in db.new:  # already existed, skip duplicate event
        pass
    else:
        _SEV_COLORS = {
            "critical": "#EF4444",
            "high": "#F97316",
            "medium": "#FBBF24",
            "low": "#10B981",
        }
        pin_color = _SEV_COLORS.get((pole.predicted_severity or "medium").lower(), "#64748B")
        event = dbm.PoleHistoryEvent(
            id=str(uuid4()),
            pole_id=pole.id,
            report_id=report_id,
            type=dbm.HistoryEventType.REPORT,
            title=title,
            author_user_id=AI_USER_ID,
            description=(
                f"Automated risk assessment: score {pole.risk_score:.1f}/100 "
                f"→ {pole.predicted_severity.upper()}"
            ),
            severity=sev,
            pin_color=pin_color,
            event_date=now,
        )
        db.add(event)

    return report
